

CREATE DATABASE IF NOT EXISTS petshop;

USE petshop;

CREATE TABLE IF NOT EXISTS pedidos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    numero VARCHAR(15) NOT NULL,
    email VARCHAR(100) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    racao VARCHAR(50) NOT NULL,
    doacao BOOLEAN NOT NULL,
    data_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);